run:
  concurrency: 8
  tests: false

linters:
  fast: false
  disable-all: true
  enable:
    - bodyclose
    - errorlint
    - exportloopref
    - funlen
    - gocognit
    - gocritic
    - gocyclo
    - gosimple
    - gosec
    - ineffassign
    - interfacer
    - staticcheck
    - maligned
    - prealloc
    - unconvert
    - whitespace

linters-settings:
  golint:
    min-confidence: 0.4

issues:
  new: false
  exclude-use-default: false
